section      DATA
DOIS: CONST CONST -2
DOIS: CONST -2.4
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE
SECTION TEXT

INPUT OLD_DATA           
;comentario
LOAD OLD_DATA; comentario
L1:L2: DIV DOIS 
STORE
DOIS
STORE  NEW_DATA ;comentario
L3:
MUL DOIS
STORE TMP_DATA ; comentario
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT OUTPUT TMP_DATA
COPY NEW_DATA,OLD_DATA
COPY NEW_DATA OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
