section      DATA
DOIS: CONST 2
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE
SECTION TEXT

INPUT OLD_DATA           
;comentario
LOAD OLD_DATA; comentario
L1: DIV DOIS 
STORE  NEW_DATA ;comentario
MUL DOIS
STORE TMP_DATA ; comentario
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA,OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
